server:
  port: 8001
  servlet:
    context-path: /

person:
  name: 约翰.斯密斯
  age: 35
  sponse: lina Smith
  children:
    - name: Jimmy Smith
      age: 6
    - name: Jenny Smith
      age: 4

spring:
  datasource:
    url: jdbc:mysql://192.168.56.102:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: SYF!123mysql
    dirver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 192.168.56.102
    port: 6379
    password:
    database: 0


